### ISSUE TITLE
Not all primitives required by MIMI necessarily happen in a room

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/mimi-arch#6]
claiming KeyPackages in MLS (similar to prekeys in DoubleRatchet) does not always happen inside a room. It is neither a "state event" or a "message event".

**Comment by bifurcation** [comment]
We discussed in email the idea that all inter-provider traffic, including KP fetches, has to transit the hub.  That seems at least pretty close to KP fetches happening in the context of a room, since the notion of a "hub" is only meaningful in the context of a room.

In other words, in the context of MIMI, you're only ever going to fetch a KP in order to add someone to a room.

**Comment by rohan-wire** [comment]
I agree that Consent and KeyPackage needs to transit the Hub. I think we need to be careful that this will eventually be about a room, but the room may never be created if the relevant consent and keys are not obtained.
